name: Deploy to Amazon EKS

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}

permissions:
  id-token: write   # Required for requesting the OIDC JWT Token
  contents: read    # Required for actions/checkout

jobs:
  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # 1. Pull the public image so it is available locally for scanning
      - name: Pull Docker Image
        run: docker pull ${{ env.IMAGE_NAME }}

      # 2. Download and Run Sysdig CLI Scanner
      - name: Sysdig Secure Image Scan
        env:
          SECURE_API_TOKEN: ${{ secrets.SYSDIG_SECURE_TOKEN }}
        run: |
          # Download the latest version of the scanner
          curl -LO "https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/latest_linux_amd64/sysdig-cli-scanner"
          chmod +x ./sysdig-cli-scanner
          

          IMAGES=$(grep -r "image:" k8s-specifications/ | awk '{print $4}')

          echo "Found the following images to scan:"
          echo "$IMAGES"

          # 3. Loop through each image: Pull & Scan
          grep -r "image:" k8s-specifications/ | awk '{print $4}' | while read img; do
            echo "-------------------START---------------------------"
            echo "Processing image: $img"
            docker pull "$img"
            echo "Scanning..."
            ./sysdig-cli-scanner --apiurl https://us4.app.sysdig.com --console-log "$img" || exit 1
          done

      # 3. Authenticate to AWS using OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      # 4. Get the kubeconfig so kubectl can talk to your cluster
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

      # 5. Apply the manifests directly
      - name: Deploy to EKS
        run: |
          # Apply the entire folder of manifests (e.g., k8s/) or a specific file
          kubectl apply -f k8s-specifications/ 
          
          # Optional: Force a restart if you need to pull the latest version of a "latest" tag
          # kubectl rollout restart deployment/vote-deployment
