name: Deploy to Amazon EKS

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}

permissions:
  id-token: write   # Required for requesting the OIDC JWT Token
  contents: read    # Required for actions/checkout

jobs:
  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Sysdig IaC Scan
        env:
          SECURE_API_TOKEN: ${{ secrets.SYSDIG_SECURE_TOKEN }}
        run: |
          # Download the latest version of the scanner
          LATEST_VERSION=$(curl -L -s https://download.sysdig.com/scanning/sysdig-cli-scanner/latest_version.txt)
          curl -LO "https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/${LATEST_VERSION}/linux/amd64/sysdig-cli-scanner"
          chmod +x ./sysdig-cli-scanner
          
          # Run the scan on the 'k8s-specifications' folder
          ./sysdig-cli-scanner --iac -r -f H \
            --apiurl https://app.us4.sysdig.com \
            k8s-specifications/ 

      # Download and Run Sysdig CLI Scanner
      - name: Sysdig Secure Image Scan
        env:
          SECURE_API_TOKEN: ${{ secrets.SYSDIG_SECURE_TOKEN }}
        run: |

          IMAGES="dockersamples/examplevotingapp_result postgres:15-alpine dockersamples/examplevotingapp_vote dockersamples/examplevotingapp_worker redis:alpine"

          # 3. Loop through each image: Pull & Scan
          for img in $IMAGES; do  
            echo "----------------------------------------------"
            echo "Processing image: $img"
            docker pull "$img"
            echo "Scanning..."
            ./sysdig-cli-scanner --apiurl https://app.us4.sysdig.com --console-log "$img" || exit 1
          done

      # Authenticate to AWS using OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      # Get the kubeconfig so kubectl can talk to your cluster
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

      # Apply the manifests directly
      - name: Deploy to EKS
        run: |
          # Apply the entire folder of manifests (e.g., k8s/) or a specific file
          kubectl apply -f k8s-specifications/ 
          
          # Optional: Force a restart if you need to pull the latest version of a "latest" tag
          # kubectl rollout restart deployment/vote-deployment
